version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb_container
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
